CREATE TABLE USER (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(50) NOT NULL,
  password VARCHAR(100) NOT NULL,
  first_name VARCHAR(50),
  last_name VARCHAR(50),
  email VARCHAR(100),
  status VARCHAR(20)
);

CREATE TABLE CUSTOMER_SERVICE (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(50) NOT NULL,
  password VARCHAR(100) NOT NULL,
  first_name VARCHAR(50),
  last_name VARCHAR(50),
  email VARCHAR(100),
  status VARCHAR(20)
);

CREATE TABLE CHATSESSION (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  client_id BIGINT,
  advisor_id BIGINT,
  started_at DATETIME,
  FOREIGN KEY (client_id) REFERENCES USER(id),
  FOREIGN KEY (advisor_id) REFERENCES CUSTOMER_SERVICE(id)
);

CREATE TABLE MESSAGE (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  chat_session_id BIGINT,
  sender_id BIGINT,
  receiver_id BIGINT,
  content TEXT,
  timestamp DATETIME,
  FOREIGN KEY (chat_session_id) REFERENCES CHATSESSION(id),
  FOREIGN KEY (sender_id) REFERENCES USER(id),
  FOREIGN KEY (receiver_id) REFERENCES CUSTOMER_SERVICE(id)
);

CREATE TABLE APPOINTMENT (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  client_id BIGINT,
  advisor_id BIGINT,
  date DATETIME,
  status VARCHAR(20),
  FOREIGN KEY (client_id) REFERENCES USER(id),
  FOREIGN KEY (advisor_id) REFERENCES CUSTOMER_SERVICE(id)
);

CREATE TABLE AGENCY (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100),
  address VARCHAR(200)
);

CREATE TABLE CATEGORY (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(50)
);

CREATE TABLE CAR (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  agency_id BIGINT,
  category_id BIGINT,
  brand VARCHAR(50),
  model VARCHAR(50),
  year INT,
  plate VARCHAR(20),
  FOREIGN KEY (agency_id) REFERENCES AGENCY(id),
  FOREIGN KEY (category_id) REFERENCES CATEGORY(id)
);

CREATE TABLE OFFER (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  car_id BIGINT,
  title VARCHAR(100),
  description TEXT,
  price DECIMAL(10,2),
  FOREIGN KEY (car_id) REFERENCES CAR(id)
);

CREATE TABLE RENTAL (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  client_id BIGINT,
  car_id BIGINT,
  offer_id BIGINT,
  appointment_id BIGINT,
  start_date DATETIME,
  end_date DATETIME,
  total_price DECIMAL(10,2),
  FOREIGN KEY (client_id) REFERENCES USER(id),
  FOREIGN KEY (car_id) REFERENCES CAR(id),
  FOREIGN KEY (offer_id) REFERENCES OFFER(id),
  FOREIGN KEY (appointment_id) REFERENCES APPOINTMENT(id)
);
